FROM python:3.10-alpine3.15
WORKDIR /app_sec_docker
RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
RUN flask reset-db
RUN python3 populate.py
EXPOSE 8002
CMD ["python3", "app.py"]